export const legacyRedirects = [
  { source: "/contacto", destination: "/es/contacto" },
  { source: "/aviso-legal", destination: "/es/aviso-legal" },
  { source: "/politica-privacidad", destination: "/es/privacidad" },
  { source: "/politica-cookies", destination: "/es/cookies" },
  { source: "/alquiler-despachos-las-palmas", destination: "/es/despachos" },
  { source: "/alquiler-oficinas-las-palmas", destination: "/es/despachos" },
  { source: "/oficina-centro-negocios", destination: "/es/despachos" },
  { source: "/nuevos-espacios", destination: "/es/despachos" },
  { source: "/business-center-las-palmas", destination: "/es/salas-de-reuniones" },
  { source: "/coworking", destination: "/es/coworking" },
  { source: "/coworking-gran-canaria", destination: "/es/coworking" },
  { source: "/que-es-coworking-y-para-que-sirve", destination: "/es/coworking" },
  { source: "/oficina-virtual-las-palmas", destination: "/es/oficina-virtual" },
  {
    source: "/centro-negocios-las-palmas/oficina-virtual-en-las-palmas-de-gran-canaria",
    destination: "/es/oficina-virtual",
  },
  { source: "/que-ofrecemos", destination: "/es" },
  { source: "/somos-sostenibles", destination: "/es/sostenibilidad" },
  { source: "/15422-2", destination: "/en" },
  { source: "/en/meeting-and-training-rooms", destination: "/en/meeting-rooms" },
  { source: "/en/office-rental-in-las-palmas", destination: "/en/private-offices" },
  { source: "/en/office-rentals-in-gran-canaria", destination: "/en/private-offices" },
  { source: "/en/shared-work-spaces", destination: "/en/coworking" },
  { source: "/en/what-is-coworking-and-what-is-it-for", destination: "/en/coworking" },
  { source: "/what-is-coworking-and-what-is-it-for", destination: "/en/coworking" },
  { source: "/why-choose-business-center-to-setup-your-office", destination: "/en/the-center" },
] as const;
